### ISSUE TITLE
Mac os m1 Not working

### ISSUE THREAD

**Issue by l3d43r** [x-Ai/BurpSuite#11]
I did all the steps and nothing ... is asking for the license

**Comment by shuaiZend** [comment]
错误: 加载主类 burp.StartBurp 时出现 LinkageError
	java.lang.UnsupportedClassVersionError: burp/StartBurp has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by l3d43r** [comment]
Still remain the same issue

**Comment by x-Ai** [comment]
use Java 17 :)
