### ISSUE TITLE
mac get license

### ISSUE THREAD

**Issue by FCCloud** [x-Ai/BurpSuite#13]
Here is an English translation of your description:

When I tried to install an app on my Mac by following the steps you provided earlier, I got an exception "EXC_CRASH (SIGKILL (Code Signature Invalid))".

To get the app to open temporarily, I ran these two commands:

sudo xattr -r -d com.apple.quarantine "/Applications/Burp Suite Professional.app"

codesign --force --deep --sign - "/Applications/Burp Suite Professional.app"

After that I was able to launch the app, but it still asks for a data license.

How can I obtain this license? Could you please advise on how to resolve this code signing issue so I can properly install and license this app on my Mac?

Let me know if you need any clarification on the problem or have additional details to share. I'd be glad to help troubleshoot further.

burp suite版本2023.6.2
<img width="561" alt="image" src="https://github.com/x-Ai/BurpSuite/assets/4635950/2c400e91-d6f4-4723-8b96-c1cdf72a3e01">

**Comment by x-Ai** [comment]
sorry, I can't provide License key. please use a search engine, I'm sure you can handle it.
