### ISSUE TITLE
ubuntu 22.04 arm64 openjdk17 环境下测试了很多个版本都不行

### ISSUE THREAD

**Issue by p1v07** [x-Ai/BurpSuite#14]
<img width="1280" alt="截屏2023-07-26 11 14 15" src="https://github.com/x-Ai/BurpSuite/assets/54148861/5299f37b-8f79-48c3-a419-6c27c575f24b">

**Comment by x-Ai** [comment]
license内容需生成。

**Comment by lyxlucky** [comment]
> license内容需生成。

怎么生成啊，萌新入坑网安

**Comment by x-Ai** [comment]
> > license内容需生成。
> 
> 怎么生成啊，萌新入坑网安

善用搜索引擎吧

**Comment by lyxlucky** [comment]
> > > license内容需生成。
> > 
> > 
> > 怎么生成啊，萌新入坑网安
> 
> 善用搜索引擎吧

谢大佬，已crack
