### ISSUE TITLE
JavaApplicationStub quit

### ISSUE THREAD

**Issue by 0xm3m** [x-Ai/BurpSuite#17]
After making changes in the Info.plist the application shows problem report.

How to fix this? 

In command-line it works perfectly.

**Comment by x-Ai** [comment]
> After making changes in the Info.plist the application shows problem report.
> 
> How to fix this?
> 
> In command-line it works perfectly.

please start burp once after fresh installation

**Comment by 0xm3m** [comment]
Now it is working but whenever I restart my system it shows the same error message again. Is that expected?

**Comment by x-Ai** [comment]
> Now it is working but whenever I restart my system it shows the same error message again. Is that expected?

based on your description, this seems to be incorrect. It is recommended to uninstall completely and reinstall.
