### ISSUE TITLE
Error in new versions

### ISSUE THREAD

**Issue by bart3nder** [x-Ai/BurpSuite#21]
Hi, After doing the instruction for Mac and trying to fix Error `The application "Burp Suite Proffesional" can't be opened.`
 by `sudo xattr -r -d com.apple.quarantine "/Applications/Burp Suite Professional.app"; codesign --force --deep --sign - "/Applications/Burp Suite Professional.app"`  I got
```
/Applications/Burp Suite Professional.app: replacing existing signature 
/Applications/Burp Suite Professional.app: resource fork, Finder information, or similar detritus not allowed
```
And burp won't open. How can I fix it?

**Comment by x-Ai** [comment]
freshly install Burp and then start it up normally once.
