### ISSUE TITLE
macOS M2 License Key pop up

### ISSUE THREAD

**Issue by mgkyawzayya** [x-Ai/BurpSuite#25]
I got this license dialog after complete all steps from ReadMe.

![Screenshot 2023-11-23 at 9 52 00 AM](https://github.com/x-Ai/BurpSuite/assets/22105402/961811a1-f4d5-497f-b6b1-c67121d076f7)

**Comment by x-Ai** [comment]
Sorry, this program does not provide a license, you will need to figure it out on your own!

**Comment by mgkyawzayya** [comment]
Yes I know. So this loader doesn't work on macOS M2? Please, can you provide me worked version number for M2?

**Comment by x-Ai** [comment]
You have provided too little information, please check your jdk or jre and please explain how to install and use burp.

**Comment by mgkyawzayya** [comment]
here is my jdk version and info.plist

openjdk 17.0.7 2023-04-18 LTS
OpenJDK Runtime Environment Corretto-17.0.7.7.1 (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (build 17.0.7+7-LTS, mixed mode, sharing)

```
<string>-Dexe4j.moduleName=$APP_PACKAGE</string>
<string>-noverify</string>
<string>--add-opens</string>
<string>java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED</string>
<string>--add-opens</string>
<string>java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED</string>
<string>-javaagent:$APP_PACKAGE/Contents/Resources/app/BurpSuiteLoader.jar</string>
```

BurpSuite Professional 2023.10.3.6 for M2

**Comment by x-Ai** [comment]
I tested it and the loader is fine. my recommendation would be to use an installer edition like burpsuite_pro_macos_arm64_v2023_x_x_x_x_x.dmg. more importantly, you need to find the available license yourself to complete the registration process!
