### ISSUE TITLE
Not Working in MAC OSX Application Mode.

### ISSUE THREAD

**Issue by secfb** [x-Ai/BurpSuite#3]
First of all, thank you for starting such a project.
I edited the Info.plist file as you described for MAC OSX computers. After the first edit it works from the shortcut in the dock. "Cannot open “Burp Suite Professional” after restarting the computer. I get an error.
The method you mentioned doesn't quite work. Do you have a suggestion about this?

**Comment by x-Ai** [comment]
Hello, if you can attach a picture to illustrate this, I should be able to help you.

**Comment by secfb** [comment]
Thanks in advance for your quick reply. I am making an adjustment as follows. I am getting an error as below. This figure after the previously working setting restarts the computer. By the way my OS version is monteray 12.4.
![1](https://user-images.githubusercontent.com/38748801/174392429-6481aa44-f792-4b46-9551-400ea4a5575c.png)

**Setting 1**
![2](https://user-images.githubusercontent.com/38748801/174392503-82c42430-d288-43e0-9a68-8d09ea684faa.png)

**Setting 2**
```
/Applications/Burp Suite Professional.app/Contents/Resources/app/BurpSuiteLoader.jar
```
I added the command in the image below to the Info.plist file.
<img width="730" alt="image" src="https://user-images.githubusercontent.com/38748801/174392630-8954444c-22b0-4784-9ed3-a2687f1bffa1.png">

I am sharing the setting I use in the zip file.
[Info.plist.zip](https://github.com/x-Ai/BurpSuite/files/8931050/Info.plist.zip)
[Orginal_Info.plist.zip](https://github.com/x-Ai/BurpSuite/files/8931058/Orginal_Info.plist.zip)

I would be really happy if you could help me with this.

**Comment by x-Ai** [comment]
I looked at your modified Info.pilst and since the contents of this file change frequently, you should now just insert the statement after line 86.

**Comment by secfb** [comment]
I get the following error.
![1](https://user-images.githubusercontent.com/38748801/174473199-f0177636-f275-4b62-a768-071c250ceb9d.png)

**Comment by x-Ai** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist SYSTEM "file://localhost/System/Library/DTDs/PropertyList.dtd">
<plist version="0.9">
<dict>
<key>CFBundleName</key>
<string>Burp Suite Professional</string>
<key>CFBundleExecutable</key>
<string>JavaApplicationStub</string>
<key>CFBundleIconFile</key>
<string>app.icns</string>
<key>CFBundleInfoDictionaryVersion</key>
<string>6.0</string>
<key>CFBundlePackageType</key>
<string>APPL</string>
<key>CFBundleSignature</key>
<string>????</string>
<key>CFBundleIdentifier</key>
<string>com.install4j.7318-9294-3757-1226.70</string>
<key>CFBundleVersion</key>
<string>2022.5.1</string>
<key>CFBundleShortVersionString</key>
<string>2022.5.1</string>
<key>CFBundleGetInfoString</key>
<string>2022.5.1</string>
<key>CFBundleDevelopmentRegion</key>
<string>en</string>
<key>NSHighResolutionCapable</key>
<true/>
<key>LSHasLocalizedDisplayName</key>
<true/>

<key>CFBundleDocumentTypes</key>
<array>
<dict>
<key>CFBundleTypeExtensions</key>
<array>
<string>burp</string>
</array>
<key>CFBundleTypeName</key>
<string>Burp Suite Project File</string>
<key>CFBundleTypeIconFile</key>
<string>assoc_burp.icns</string>
<key>CFBundleTypeRole</key>
<string>Editor</string>
</dict>
</array>
<!-- I4J_INSERT_DOCTYPE -->
<!-- I4J_INSERT_URLTYPE -->
<key>i4j.baseDir</key>
<string>$APP_PACKAGE/Contents/Resources/app/</string>
<key>LSMinimumSystemVersion</key>
<string>10.11</string>
<key>i4j.appId</key>
<string>7318-9294-3757-1226</string>
<key>i4j.allowPassthrough</key>
<true/>
<key>i4j.minVersion</key>
<string>12.0.2</string>
<key>i4j.maxVersion</key>
<string></string>
<key>i4j.vmIdPrefix</key>
<string></string>
<key>JavaVM</key>
<dict>
<key>MainClass</key>
<string>com.install4j.runtime.launcher.MacLauncher</string>
<key>VMOptionArray</key>
<array>
<string>-Dfile.encoding=UTF-8</string>
<string>--add-opens</string>
<string>java.base/java.lang=ALL-UNNAMED</string>
<string>--add-opens</string>
<string>java.base/javax.crypto=ALL-UNNAMED</string>
<string>--add-opens</string>
<string>java.desktop/javax.swing=ALL-UNNAMED</string>
<string>--add-opens</string>
<string>java.desktop/java.awt=ALL-UNNAMED</string>
<string>--add-opens</string>
<string>java.desktop/java.awt.color=ALL-UNNAMED</string>
<string>-noverify</string>
<string>-javaagent:$APP_PACKAGE/Contents/Resources/app/BurpSuiteLoader.jar</string>
<string>--add-opens</string>
<string>jdk.crypto.cryptoki/sun.security.pkcs11=ALL-UNNAMED</string>
<string>-Dinstall4j.launcherId=70</string>
<string>-Dinstall4j.swt=false</string>
<string>-Dexe4j.moduleName=$APP_PACKAGE</string>
<string>-noverify</string>
<string>-javaagent:$APP_PACKAGE/Contents/Resources/app/BurpSuiteLoader.jar</string>
</array>
<key>OptionsFile</key>
<string>$APP_PACKAGE/Contents/vmoptions.txt</string>
<key>ArgumentArray</key>
<array>
</array>
<key>SearchSequence</key>
<array>
<string>Y</string>
<string>EJAVA_HOME</string>
<string>EJDK_HOME</string>
</array>
<key>VersionInfo</key>
<string>0_183916422</string>
<key>SplashFile</key>
<string>$APP_PACKAGE/Contents/Resources/app/.install4j/s_sl5vaz.png</string>
<key>ClassPath</key>
<string>$APP_PACKAGE/Contents/Resources/app/.install4j/i4jruntime.jar:$APP_PACKAGE/Contents/Resources/app/burpsuite_pro.jar</string><!-- I4J_INSERT_CLASSPATH -->
<key>WorkingDirectory</key>
<string>$APP_PACKAGE/Contents/Resources/app/./.</string>
</dict>
</dict>
</plist>
```

**Comment by secfb** [comment]
By the way, I'm getting the first error I wrote. Unfortunately it still doesn't work.

<img width="258" alt="image" src="https://user-images.githubusercontent.com/38748801/174749677-36d06ae2-00ef-4a77-bc51-023f5e8af127.png">

**Comment by x-Ai** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist SYSTEM "file://localhost/System/Library/DTDs/PropertyList.dtd">
<plist version="0.9">
<dict>
<key>CFBundleName</key>
<string>Burp Suite Professional</string>
<key>CFBundleExecutable</key>
<string>JavaApplicationStub</string>
<key>CFBundleIconFile</key>
<string>app.icns</string>
<key>CFBundleInfoDictionaryVersion</key>
<string>6.0</string>
<key>CFBundlePackageType</key>
<string>APPL</string>
<key>CFBundleSignature</key>
<string>????</string>
<key>CFBundleIdentifier</key>
<string>com.install4j.7318-9294-3757-1226.70</string>
<key>CFBundleVersion</key>
<string>2022.5.1</string>
<key>CFBundleShortVersionString</key>
<string>2022.5.1</string>
<key>CFBundleGetInfoString</key>
<string>2022.5.1</string>
<key>CFBundleDevelopmentRegion</key>
<string>en</string>
<key>NSHighResolutionCapable</key>
<true/>
<key>LSHasLocalizedDisplayName</key>
<true/>

<key>CFBundleDocumentTypes</key>
<array>
<dict>
<key>CFBundleTypeExtensions</key>
<array>
<string>burp</string>
</array>
<key>CFBundleTypeName</key>
<string>Burp Suite Project File</string>
<key>CFBundleTypeIconFile</key>
<string>assoc_burp.icns</string>
<key>CFBundleTypeRole</key>
<string>Editor</string>
</dict>
</array>


<key>i4j.baseDir</key>
<string>$APP_PACKAGE/Contents/Resources/app/</string>
<key>LSMinimumSystemVersion</key>
<string>10.11</string>
<key>i4j.appId</key>
<string>7318-9294-3757-1226</string>
<key>i4j.allowPassthrough</key>
<true/>
<key>i4j.minVersion</key>
<string>12.0.2</string>
<key>i4j.maxVersion</key>
<string></string>
<key>i4j.vmIdPrefix</key>
<string></string>
<key>JavaVM</key>
<dict>
<key>MainClass</key>
<string>com.install4j.runtime.launcher.MacLauncher</string>
<key>VMOptionArray</key>
<array>
<string>-Dfile.encoding=UTF-8</string>
<string>--add-opens</string>
<string>java.base/java.lang=ALL-UNNAMED</string>
<string>--add-opens</string>
<string>java.base/javax.crypto=ALL-UNNAMED</string>
<string>--add-opens</string>
<string>java.desktop/javax.swing=ALL-UNNAMED</string>
<string>--add-opens</string>
<string>java.desktop/java.awt=ALL-UNNAMED</string>
<string>--add-opens</string>
<string>java.desktop/java.awt.color=ALL-UNNAMED</string>
<string>--add-opens</string>
<string>jdk.crypto.cryptoki/sun.security.pkcs11=ALL-UNNAMED</string>
<string>-Dinstall4j.launcherId=70</string>
<string>-Dinstall4j.swt=false</string>
<string>-Dexe4j.moduleName=$APP_PACKAGE</string>
<string>-noverify</string>
<string>-javaagent:$APP_PACKAGE/Contents/Resources/app/BurpSuiteLoader.jar</string>
</array>
<key>OptionsFile</key>
<string>$APP_PACKAGE/Contents/vmoptions.txt</string>
<key>ArgumentArray</key>
<array>
</array>
<key>SearchSequence</key>
<array>
<string>Y</string>
<string>EJAVA_HOME</string>
<string>EJDK_HOME</string>
</array>
<key>VersionInfo</key>
<string>0_183916422</string>
<key>SplashFile</key>
<string>$APP_PACKAGE/Contents/Resources/app/.install4j/s_sl5vaz.png</string>
<key>ClassPath</key>
<string>$APP_PACKAGE/Contents/Resources/app/.install4j/i4jruntime.jar:$APP_PACKAGE/Contents/Resources/app/burpsuite_pro.jar</string>
<key>WorkingDirectory</key>
<string>$APP_PACKAGE/Contents/Resources/app/./.</string>
</dict>
</dict>
</plist>

**Comment by 4rat** [comment]
> 

使用macwk小助手修复一下签名即可

**Comment by x-Ai** [comment]
> By the way, I'm getting the first error I wrote. Unfortunately it still doesn't work.
> 
> <img alt="image" width="258" src="https://user-images.githubusercontent.com/38748801/174749677-36d06ae2-00ef-4a77-bc51-023f5e8af127.png">

Use this file.
[Info.plist.zip](https://github.com/x-Ai/BurpSuite/files/8984117/Info.plist.zip)

**Comment by 4rat** [comment]
> 

https://www.macwk.com/soft/macos-assistant-macwk
绕过签名 + 签名

**Comment by secfb** [comment]
By the way, I'm getting the first error I wrote. Unfortunately it still doesn't work.


> Info.plist.zip

It happens the first time it does but when I restart the computer I get the same error. After restarting, there is no change in the Info.plist file. But for some reason it doesn't.

**Comment by secfb** [comment]
> https://www.macwk.com/soft/macos-assistant-macwk
> 绕过签名 + 签名

Wouldn't it be better if you give some details on how it's done?

**Comment by 7a6163** [comment]
> > https://www.macwk.com/soft/macos-assistant-macwk
> > 绕过签名 + 签名
> 
> Wouldn't it be better if you give some details on how it's done?

`sudo xattr -r -d com.apple.quarantine "/Applications/Burp Suite Professional.app"`

**Comment by secfb** [comment]
> > > https://www.macwk.com/soft/macos-assistant-macwk
> > > 绕过签名 + 签名
> > 
> > 
> > Wouldn't it be better if you give some details on how it's done?
> 
> `sudo xattr -r -d com.apple.quarantine "/Applications/Burp Suite Professional.app"`

The issue has nothing to do with your command. You already need permission to open the jar file once.

**Comment by 7a6163** [comment]
Hello @secfb
Can you remove the old burp suite and reinstall it?

Move `BurpSuiteLoader.jar` to `/Applications/Burp Suite Professional.app/Contents/Resources/app/BurpSuiteLoader`

Modify `/Applications/Burp Suite Professional.app/Contents/Info.plist`
```xml
<string>-Dexe4j.moduleName=$APP_PACKAGE</string>
<string>-noverify</string>
<string>-javaagent:$APP_PACKAGE/Contents/Resources/app/BurpSuiteLoader.jar</string>
```

Finally, execute the commands.

```
sudo xattr -r -d com.apple.quarantine "/Applications/Burp Suite Professional.app"
codesign --force --deep --sign - /Applications/Burp\ Suite\ Professional.app
```

**Comment by CraKeyBoy** [comment]
@7a6163 
sudo codesign --force --deep --sign - "/Applications/Burp Suite Professional.app"
2022-07-22 13:19:08.770 codesign[6719:23493771] There was an error parsing the Info.plist for the bundle at URL <0x6000020a40a0>: NSCocoaErrorDomain - 3840
/Applications/Burp Suite Professional.app: replacing existing signature
2022-07-22 13:19:08.773 codesign[6719:23493771] There was an error parsing the Info.plist for the bundle at URL <0x6000020a03c0>: NSCocoaErrorDomain - 3840

**Comment by secfb** [comment]
> /Applications/Burp Suite Professional.app/Contents/Info.plist

Thank you very much for your answer. It happened when I did as you said. I shut down the computer and restarted it. The program worked without problems. I ran the program via Launchpad. I'm using it now without any problems.

**Comment by wind315** [comment]
> Hello @secfb Can you remove the old burp suite and reinstall it?
> 
> Move `BurpSuiteLoader.jar` to `/Applications/Burp Suite Professional.app/Contents/Resources/app/`
> 
> Modify `/Applications/Burp Suite Professional.app/Contents/Info.plist`
> 
> ```
> <string>-Dexe4j.moduleName=$APP_PACKAGE</string>
> <string>-noverify</string>
> <string>-javaagent:$APP_PACKAGE/Contents/Resources/app/BurpSuiteLoader.jar</string>
> ```
> 
> Finally, execute the commands.
> 
> ```
> sudo xattr -r -d com.apple.quarantine "/Applications/Burp Suite Professional.app"
> codesign --force --deep --sign - "/Applications/Burp Suite Professional.app"
> ```

我也遇到同楼主一样的问题，这个很管用，不过能解释下这两条命令起啥作用么？谢谢
