### ISSUE TITLE
运行burpsuite_pro.jar报错

### ISSUE THREAD

**Issue by crithes** [x-Ai/BurpSuite#31]
运行：java "--add-opens=java.desktop/javax.swing=ALL-UNNAMED" "--add-opens=java.base/java.lang=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED" "-javaagent:BurpLoaderKeygen.jar" "-noverify" "-jar" "/Applications/Burp Suite Professional.app/Contents/Resources/app/burpsuite_pro.jar"报错：Github:https://github.com/h3110w0r1d-y/BurpLoaderKeygen 商业使用请购买正版软件！
错误: 加载主类 burp.StartBurp 时出现 LinkageError
	java.lang.UnsupportedClassVersionError: burp/StartBurp has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by x-Ai** [comment]
您好，请注意你的Java版本。
