### ISSUE TITLE
Professional 2022.9.5 License Error

### ISSUE THREAD

**Issue by secfb** [x-Ai/BurpSuite#6]
It does not support the new version(Burp Suite Professional 2022.9.5). Any chance of an update?

**Comment by x-Ai** [comment]
> It does not support the new version(Burp Suite Professional 2022.9.5). Any chance of an update?

after testing, Loader has no problem, please check the way to use.

![Burp](https://user-images.githubusercontent.com/5061489/199178505-f7d5d06f-8223-4f61-9687-9da7b0351eb1.png)

**Comment by secfb** [comment]
It doesn't work in the new version. Can you check? Professional 2022.11
